In [2]:
square=[]

for i in range(10):
    square.append(i**2)
square

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [2]:
square=[i**2 for i in range(10)]
print(square)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [3]:
square=[i**2 for i in range(30)if i%3==0]
square

[0, 9, 36, 81, 144, 225, 324, 441, 576, 729]

In [2]:
square={i:i**2 for i in range(20)if i%2==0}
square

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64, 10: 100, 12: 144, 14: 196, 16: 256, 18: 324}

In [3]:
square_rev={square[key]:key for key in square}
square_rev

{0: 0, 4: 2, 16: 4, 36: 6, 64: 8, 100: 10, 144: 12, 196: 14, 256: 16, 324: 18}

In [4]:
sum([i**2 for i in range(10)])

285

In [11]:
words=open('/home/midhun/Documents/python_workshop/words.txt','r')
words

<_io.TextIOWrapper name='/home/midhun/Documents/python_workshop/words.txt' mode='r' encoding='UTF-8'>

In [12]:
wordlist=words.readlines()

In [14]:
wordlist[:]

['a\n',
 'ability\n',
 'able\n',
 'about\n',
 'above\n',
 'accept\n',
 'according\n',
 'account\n',
 'across\n',
 'act\n',
 'action\n',
 'activity\n',
 'actually\n',
 'add\n',
 'address\n',
 'administration\n',
 'admit\n',
 'adult\n',
 'affect\n',
 'after\n',
 'again\n',
 'against\n',
 'age\n',
 'agency\n',
 'agent\n',
 'ago\n',
 'agree\n',
 'agreement\n',
 'ahead\n',
 'air\n',
 'all\n',
 'allow\n',
 'almost\n',
 'alone\n',
 'along\n',
 'already\n',
 'also\n',
 'although\n',
 'always\n',
 'American\n',
 'among\n',
 'amount\n',
 'analysis\n',
 'and\n',
 'animal\n',
 'another\n',
 'answer\n',
 'any\n',
 'anyone\n',
 'anything\n',
 'appear\n',
 'apply\n',
 'approach\n',
 'area\n',
 'argue\n',
 'arm\n',
 'around\n',
 'arrive\n',
 'art\n',
 'article\n',
 'artist\n',
 'as\n',
 'ask\n',
 'assume\n',
 'at\n',
 'attack\n',
 'attention\n',
 'attorney\n',
 'audience\n',
 'author\n',
 'authority\n',
 'available\n',
 'avoid\n',
 'away\n',
 'baby\n',
 'back\n',
 'bad\n',
 'bag\n',
 'ball\n',
 'bank\

In [15]:
len(wordlist)

1000

In [16]:
wordlist[0].strip().lower()

'a'

In [17]:
wordclean=[words.strip().lower()for words in wordlist]

In [18]:
wordclean[:10]

['a',
 'ability',
 'able',
 'about',
 'above',
 'accept',
 'according',
 'account',
 'across',
 'act']

In [19]:
wordsunique=list(set(wordclean))
wordsunique

['watch',
 'after',
 'care',
 'great',
 'particularly',
 'against',
 'company',
 'death',
 'best',
 'away',
 'of',
 'test',
 'guy',
 'building',
 'perhaps',
 'skin',
 'young',
 'attention',
 'their',
 'oh',
 'professional',
 'put',
 'nice',
 'your',
 'although',
 'pass',
 'thousand',
 'board',
 'court',
 'hang',
 'well',
 'with',
 'whole',
 'box',
 'try',
 'everything',
 'above',
 'know',
 'give',
 'activity',
 'article',
 'modern',
 'environment',
 'hold',
 'begin',
 'democratic',
 'old',
 'yourself',
 'hear',
 'life',
 'note',
 'similar',
 'to',
 'fund',
 'must',
 'personal',
 'high',
 'middle',
 'read',
 'sport',
 'stand',
 'success',
 'many',
 'enjoy',
 'if',
 'left',
 'on',
 'son',
 'research',
 'right',
 'under',
 'anyone',
 'you',
 'cancer',
 'human',
 'pressure',
 'issue',
 'experience',
 'north',
 'sign',
 'suggest',
 'soldier',
 'scientist',
 'including',
 'kitchen',
 'them',
 'town',
 'enough',
 'husband',
 'understand',
 'view',
 'collection',
 'whom',
 'as',
 'it',
 'centr

In [20]:
wordsunique.sort()

In [21]:
def signature(word):
    return ''.join(sorted(word))

In [23]:
signature("midh un")

' dhimnu'

In [27]:
def anagrams(mywords):
    return[word for word in wordclean if signature(word)==signature(mywords)]

In [28]:
anagrams('cat')

['act']

### Numpy

In [29]:
import numpy as np
import matplotlib.pyplot as plt

In [30]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [31]:
a.dtype

dtype('int64')

In [32]:
a=np.array([1,2,3,4,5],dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [33]:
a.ndim,a.shape,a.size

(1, (5,), 5)

In [34]:
b=np.array([[1,2,3,4],[6,7,8,9]])

In [35]:
b.ndim,b.shape,b.size

(2, (2, 4), 8)

In [36]:
np.zeros((2,2),'d')

array([[0., 0.],
       [0., 0.]])